Lecture 1
js-tasks-ru/htmlcss-20240412_jessamineoliva16661814 pull request #3
Opened 2024-04-22 18:23 UTC by WilliamBj2

2024-04-22 18:23 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-25 14:44 UTC, GSemikozov requested changes

2024-04-25 14:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
ни в коем случае) наоборот - компоненты подключаем в main, чтобы они были доступны глобально

2024-04-25 14:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 182px;
лишнее ограничение

2024-04-25 14:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 182px;
не хватает паддингов и описания стилей текста

2024-04-25 14:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled {
disabled общий и одинаковый для всех типов

2024-04-29 14:37 UTC, GSemikozov requested changes

2024-04-29 14:37 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 0 14.25px 0;
по краям тоже нужны (проверка: добавить текст `fgkvndgfknvjsncnefvlndcd`)

2024-04-29 14:37 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-family: inherit;
неа, именно Roboto

2024-05-02 13:59 UTC, GSemikozov approved these changes

2024-05-02 13:59 UTC, merged